apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbackrest-config
  namespace: {{ .Release.Namespace }}
data:
  pgbackrest.conf: |
    [global]
    # Configuration du stockage S3 vers AWS
    repo1-type=s3
    repo1-path=/pgbackrest
    repo1-s3-bucket=votre-nom-de-bucket-s3-backups
    repo1-s3-region=eu-west-3
    repo1-s3-endpoint=s3.eu-west-3.amazonaws.com
    # Pas besoin de clés d'accès ici, AWS IRSA gère l'authentification de manière fluide
    
    # Rétention (Exemple : garder 7 jours de backups complets)
    repo1-retention-full=7
    
    # Log
    log-level-console=info
    log-level-file=detail

    [db-main]
    pg1-path=/bitnami/postgresql/data