apiVersion: batch/v1
kind: CronJob
metadata:
  name: pgbackrest-backup-cron
  namespace: {{ .Release.Namespace }}
spec:
  # Exécution tous les jours à minuit
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          # Utilise le même ServiceAccount pour hériter des droits S3
          serviceAccountName: {{ include "postgresql.v1.primary.serviceAccountName" .Subcharts.postgresql }}
          restartPolicy: OnFailure
          containers:
            - name: pgbackrest-backup
              # Utilisation de l'image Bitnami Postgres qui contient déjà pgbackrest
              image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: IfNotPresent
              command:
                - bash
                - -c
                - |
                  echo "Démarrage de la sauvegarde avec pgBackRest..."
                  # Initialise la Stanza si elle n'existe pas (nécessaire au tout premier lancement)
                  pgbackrest --stanza=db-main stanza-create --log-level-console=info || true
                  # Lance un backup incrémental (AWS S3)
                  pgbackrest --stanza=db-main backup --type=incr
              volumeMounts:
                - name: pgbackrest-config
                  mountPath: /etc/pgbackrest
                - name: pg-data
                  mountPath: /bitnami/postgresql/data
          volumes:
            - name: pgbackrest-config
              configMap:
                name: pgbackrest-config
            # Accès au volume de données existant de Postgres
            - name: pg-data
              persistentVolumeClaim:
                claimName: {{ include "postgresql.v1.primary.fullname" .Subcharts.postgresql }}