- name: Create kubectl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link
  
- name: Create .kube directory
  file:
    path: /home/rocky/.kube
    state: directory
    owner: rocky
    group: rocky
    mode: "0755"
  
- name: Copy kubeconfig
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /home/rocky/.kube/config
    remote_src: true
    owner: rocky
    group: rocky
    mode: "0600"

- name: Create postgres namespace
  command: /usr/local/bin/kubectl create namespace postgres
  ignore_errors: true
  environment:
    KUBECONFIG: /home/rocky/.kube/config
  register: create_ns_result
  failed_when: 
    - create_ns_result.rc != 0 
    - "'already exists' not in create_ns_result.stderr"

- name: Add Bitnami Helm repo
  command: /usr/local/bin/helm repo add bitnami https://charts.bitnami.com/bitnami
  ignore_errors: true

- name: Update Helm repos
  command: /usr/local/bin/helm repo update

- name: Copy values-postgresql.yml file
  copy:
    src: /home/dataops/aws-kube-postgres/ansible/roles/postgres/files/values-postgresql.yml
    dest: /tmp/values-postgresql.yml

- name: Check Helm/Kubectl
  command: /usr/local/bin/helm version --kubeconfig /home/rocky/.kube/config
  register: helm_check
  ignore_errors: true

- name: Display check result
  debug:
    var: helm_check

- name: Deploy PostgreSQL
  command: >
    /usr/local/bin/helm upgrade --install postgres bitnami/postgresql
    -n postgres
    -f /tmp/values-postgresql.yml  
  environment:
    KUBECONFIG: /home/rocky/.kube/config

- name: Start PostgreSQL port-forward in background
  shell: |
    nohup /usr/local/bin/kubectl port-forward \
      --kubeconfig=/home/rocky/.kube/config \
      --namespace postgres \
      svc/postgres-postgresql 5432:5432 \
      --address 0.0.0.0 \
      > /tmp/postgres-portforward.log 2>&1 &
  args:
    executable: /bin/bash

- name: Wait a few seconds for the tunnel to be established
  pause:
    seconds: 3

- name: Display pf_register
  debug:
    var: item
  loop:
    - "{{ pf_result.stdout_lines | default([]) }}"
    - "{{ pf_result.stderr_lines | default([]) }}"