#--
apiVersion: v2
name: postgres-gitops
description: Application PostgreSQL avec pgBackRest et stockage S3 via ArgoCD
type: application
version: 1.0.0
appVersion: "16"

dependencies:
  - name: postgresql
    version: 15.5.3 # Version du Chart Helm Bitnami
    repository: https://charts.bitnami.com/bitnami