postgresql:
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: 15.13.0-debian-12-r0

postgresql:
  image:
    registry: public.ecr.aws
    repository: bitnami/postgresql
    tag: 16.4.0

  auth:
    database: "devdb"
    postgresPassword: "postgres123"

  primary:
    persistence:
      enabled: true
      storageClass: "gp3"
      size: 10Gi

    serviceAccount:
      create: true
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/votre-role-iam-pgbackrest"

    extendedConfiguration: |
      archive_mode = on
      archive_command = 'pgbackrest --stanza=db-main archive-push %p'
      wal_level = replica
      max_wal_senders = 10

    extraVolumeMounts:
      - name: pgbackrest-config
        mountPath: /etc/pgbackrest

    extraVolumes:
      - name: pgbackrest-config
        configMap:
          name: pgbackrest-config