global:
  security:
    allowInsecureImages: true

image:
  registry: public.ecr.aws
  repository: bitnami/postgresql
  tag: 16.4.0

auth:
  database: "devdb"
  postgresPassword: "postgres123"

primary:
  persistence:
    enabled: true
    storageClass: "local-path"
    size: 10Gi

  service:
    type: NodePort
    nodePorts:
      postgresql: 30564